vm_settings: &vm_settings
  working_directory: ~/app
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  build:
    <<: *vm_settings
    steps:
      - attach_workspace:
          at: ~/app/node_modules

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn run build

      - run: echo 'aws sync goes here'

  test:
    <<: *vm_settings
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn run lint

      - persist_to_workspace:
          root: node_modules
          paths:
            - .

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
